export const works = [
    {
        name: "thunderSearch",
        description: 'This is a simple full search implementation that search accurately and semantically with the power of PostgreSQL and Upstash Vector.',
        img: 'thunderSearch.png',
        languages: ['next', 'shadcn-ui', 'tailwind', 'typescript'],
        htmlLink: "https://thunder-search.vercel.app",
        githubLink: "https://github.com/Kei-K23/thunderSearch",
    },
    {
        name: "nuxt-crm",
        description: 'This is practical Nuxt CRM application',
        img: 'nuxtcrm.png',
        languages: ['vue3', 'nuxt', 'tailwind', 'typescript'],
        htmlLink: "https://nuxt-crm-sigma.vercel.app",
        githubLink: "https://github.com/Kei-K23/nuxt-crm",
    },
    {
        name: "vue-todo-app",
        description: 'Drag and drop todo application using Vue 3 with Composition API',
        img: 'vuetodo.png',
        languages: ['vue3', 'dasiyui'],
        htmlLink: "https://vue-todo-app-beige.vercel.app",
        githubLink: "https://github.com/Kei-K23/vue-todo-app",
    },
    {
        name: "go-blog-app",
        description: 'Go blog app with Templ',
        img: '',
        languages: ['golang', 'echo', 'turso'],
        htmlLink: "https://vue-todo-app-beige.vercel.app",
        githubLink: "https://github.com/Kei-K23/vue-todo-app",
    },
    {
        name: "collector",
        description: 'This is collector online survey application like Google Form.',
        img: 'collector.png',
        languages: ['next', 'typescript', 'tailwind', 'shadcn-ui'],
        htmlLink: "https://collector-psi.vercel.app",
        githubLink: "https://github.com/Kei-K23/collector",
    },
    {
        name: "collector",
        description: 'This is Nestjs Blog API with user authentication with JWT token. User can create, delete and update the blog.',
        img: '',
        languages: ['nest', 'typescript', 'postgresql'],
        htmlLink: "https://nestjs-blog-api-rpbn.onrender.com/api",
        githubLink: "https://github.com/Kei-K23/nestjs-blog-api",
    },
    {
        name: "connectify",
        description: 'This is connectify web application that have some core functionalities but different implementation like Thread (an Instagram application).',
        img: 'connectify.png',
        languages: ['next', 'typescript', 'tailwind', 'shadcn-ui'],
        htmlLink: "https://connectify-kei.onrender.com",
        githubLink: "https://github.com/Kei-K23/connectify",
    },
    {
        name: "streamify",
        description: 'Streamify is a streaming web app(like Twitch) that can connect your favorite streaming software. Provide simple communication with your viewers and other essential features that need in streaming application.',
        img: 'streamify.png',
        languages: ['next', 'typescript', 'tailwind', 'stripe', 'shadcn-ui'],
        htmlLink: "https://streamify-sigma.vercel.app",
        githubLink: "https://github.com/Kei-K23/streamify",
    },
    {
        name: "task-mingle",
        description: 'TaskMingle is collaborative workspace for task management for your teams and organizations. It provide powerful task management feature with better user design and user experience.',
        img: 'taskmingle.png',
        languages: ['next', 'typescript', 'tailwind', 'stripe', 'shadcn-ui'],
        htmlLink: "https://task-mingle-phi.vercel.app",
        githubLink: "https://github.com/Kei-K23/task-mingle",
    },
    {
        name: "bit-book",
        description: 'This is book management CRUD project.',
        img: 'bitbook.png',
        languages: ['next', 'typescript', 'tailwind', 'shadcn-ui'],
        htmlLink: "https://bit-book-kei-k23.vercel.app",
        githubLink: "https://github.com/Kei-K23/bit-book",
    },
    {
        name: "notehub-kei-k",
        description: 'This is notes sharing and collaboration web application for everyone and every team with simple and easy to use with minimalist design.',
        img: 'notehub.png',
        languages: ['next', 'typescript', 'tailwind'],
        htmlLink: "https://notehub-kei-k.vercel.app",
        githubLink: "https://github.com/Kei-K23/notehub",
    },
    {
        name: "my-portfolio",
        description: 'This is My Portfolio website (old one).',
        img: 'oldportfolio.png',
        languages: ['next', 'typescript', 'tailwind'],
        htmlLink: "https://my-portfolio-teal-seven.vercel.app",
        githubLink: "https://github.com/Kei-K23/my-portfolio",
    },
    {
        name: "breeze",
        description: 'Breeze is a modern chat application designed to facilitate seamless communication between friends and groups.',
        img: 'breeze.png',
        languages: ['express', 'next', 'typescript'],
        htmlLink: "https://breeze-chat-kei.onrender.com",
        githubLink: "https://github.com/Kei-K23/breeze",
    },
    {
        name: "nike-landing-website",
        description: 'This is simple React and Tailwind CSS landing website.',
        img: 'nikelanding.png',
        languages: ['react', 'javascript', 'tailwind'],
        htmlLink: "https://nike-landing-website.vercel.app",
        githubLink: "https://github.com/Kei-K23/nike-landing-website",
    },
    {
        name: "password-generator",
        description: 'A web application to generate strong passwords and manage saved passwords using JavaScript and Tailwind.',
        img: 'passwordgenerator.png',
        languages: ['tailwind', 'javascript'],
        htmlLink: "https://password-generator-six-sigma.vercel.app",
        githubLink: "https://github.com/Kei-K23/password-generator",
    },
    {
        name: "pizza-time-webapp",
        description: 'This is simple and basic pizza ordering website that build with React + TypeScript + Tailwind CSS.',
        img: 'pizzaTime.png',
        languages: ['react', 'typescript', 'tailwind', 'react-router'],
        htmlLink: "https://pizza-time-webapp.vercel.app",
        githubLink: "https://github.com/Kei-K23/pizza-time-webapp",
    },
    {
        name: "movie-man-web-application",
        description: 'This is movie- man web application.',
        img: 'movieman.png',
        languages: ['react', 'react-router', 'tailwind', 'moviedb'],
        htmlLink: "https://movie-man-web-application.vercel.app",
        githubLink: "https://github.com/Kei-K23/movie-man-web-application",
    },
    {
        name: "summarizar-webapp",
        description: 'This is web application for article summarization web application that power by Article Extractor and Summarizer from Rapid API.',
        img: 'summarizar.png',
        languages: ['react', 'javascript', 'tailwind', 'react-toolkit'],
        htmlLink: "https://summarizar-webapp-foe1.vercel.app",
        githubLink: "https://github.com/Kei-K23/summarizar-webapp",
    },
    {
        name: "save-up-expense-tracker",
        description: 'This is small expense tracker web application that provide to tracker budget and expenses. Using React, tailwind and LocalStorage Web API.',
        img: 'saveup.png',
        languages: ['react', 'javascript', 'tailwind'],
        htmlLink: 'https://save-up-expense-tracker.vercel.app/',
        githubLink: 'https://github.com/Kei-K23/saveUp-expense-tracker'
    }
]